# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=20, unique=True)),
                ('dhcp_fingerprint', models.CharField(max_length=256, null=True)),
                ('dhcp_vendor', models.CharField(max_length=256, null=True)),
                ('hostname', models.CharField(max_length=256, null=True)),
                ('mode', models.CharField(choices=[(b'SL', b'Silent'), (b'NJ', b'Ninja'), (b'NO', b'No Mode')], default=b'SL', max_length=2)),
                ('chosen_name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.TextField(unique=True)),
                ('model', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='user_agent',
            field=models.ManyToManyField(to='devices.UserAgent'),
        ),
    ]
