# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 13:50
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import lib.utils


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_deviceentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceentry',
            name='changing',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceentry',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=lib.utils.secure_random_id, unique=True),
        ),
    ]
