# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20170731_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceentry',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
