# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DnsmasqBlockedLogEntry',
        ),
        migrations.DeleteModel(
            name='DnsmasqQueryLogEntry',
        ),
        migrations.DeleteModel(
            name='PrivoxyLogEntry',
        ),
    ]
