#! /bin/bash

### BEGIN INIT INFO
# Provides: apate
# Required-Start: $local_fs $remote_fs $network $syslog $all
# Should-Start:
# Required-Stop: $local_fs $remote_fs $network $syslog
# Should-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: ARP Spoofing Daemon
# Description:    Runs up the ARP Spoofing Daemon process
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

if [[ $EUID -ne 0 ]]; then
   echo "This daemon must be run as root"
   exit 1
fi

# Activate the python virtual environment
. /opt/apate/venv/bin/activate

PID={{ default_settings.apate.pid.dir }}
LOGDIR={{ default_settings.log.general.path }}/{{ default_settings.log.apate.subdir }}

if [ ! -d $PID ]; then
    mkdir $PID || return 2
fi

if [ ! -d $LOGDIR ]; then
    mkdir $LOGDIR || return 2
fi

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python /opt/apate/apate.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /opt/apate/apate.py stop
    ;;
  restart)
    echo "Restarting server"
    python /opt/apate/apate.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/apate {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
